### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by Aakashsaini-0** [mullatoez/finger-print-auth---starter-code#1]
![2021-06-05 (1)](https://user-images.githubusercontent.com/72099630/120861857-94b38200-c5a5-11eb-9207-7d608b17ad2a.png)
![2021-06-05 (2)](https://user-images.githubusercontent.com/72099630/120861864-98470900-c5a5-11eb-99af-219b8791fbe8.png)
![2021-06-05](https://user-images.githubusercontent.com/72099630/120861874-9aa96300-c5a5-11eb-903c-35de58e35f3e.png)
![2021-06-05 (3)](https://user-images.githubusercontent.com/72099630/120861929-b14fba00-c5a5-11eb-98be-2822a21f9908.png)
help!!1

**Comment by mullatoez** [comment]
Hello,

Do you have the biometric authentication dependency?

implementation 'androidx.biometric:biometric:1.0.1'

**Comment by Aakashsaini-0** [comment]
don't know

**Comment by mullatoez** [comment]
You need to add the dependency

implementation("androidx.biometric:biometric:1.2.0-alpha03")

Then make sure you are using androidx.biometric object i.e this line here

 private lateinit var biometricPrompt: BiometricPrompt  // should be of androidx.biometric

**Comment by Aakashsaini-0** [comment]
seriously don't know about androidx.biometric
help!

**Comment by mullatoez** [comment]
That's the dependency you will need for integrating biometric auth in your app.
If you read this official android documentation you will understand what am talking about

https://developer.android.com/jetpack/androidx/releases/biometric
